- hosts: all
  name: Playbook to ping all hosts
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
      register: ping
    - name: Set stats
      ansible.builtin.set_stats:
        data: "{{ ping }}"
